### ISSUE TITLE
无法调试，无法接收回复？

### ISSUE THREAD

**Issue by hmf1235789** [YEZZESDXHN/UDS_Client#1]
下载Releases版本UDS.Client.v1.3可以正常运行，收发数据。
![发布版本可以](https://github.com/user-attachments/assets/a07ed366-34d6-4c25-918b-2337993a2c69)

想修改下载流程，用Vscode发现不能调试，打断点无效
![无法打断点](https://github.com/user-attachments/assets/cd2ab589-4a5a-4c0d-9032-ce2c6f0a0311)

并且实际有回复报文，和Releases exe回复报文一致，但debug无法接收到报文，显示接收超时
![实际回复有报文](https://github.com/user-attachments/assets/d681eacf-46a7-4e7e-a22a-ab7fd6f59914)

是否需要设置那里才能调试？谢谢

**Comment by YEZZESDXHN** [comment]
我用的pycharm
